action                 = "create"
url                    = "http://trusted-provider/cgi-bin/csaf_provider.go"
tlp                    = "csaf"
external_signed        = false
no_schema_check        = false
# key                  = "/path/to/openpgp/key/file"       # not set by default
password               = "secretpassword" # not set by default
# passphrase           = "OpenPGP passphrase"              # not set by default
# client_cert          = "/path/to/client/cert"            # not set by default
# client_key           = "/path/to/client/cert.key"        # not set by default
# client_passphrase    = "client cert passphrase"          # not set by default
password_interactive   = false
passphrase_interactive = false
insecure               = true
