server {
    listen 80 default_server;
    #listen 443 ssl;

    root /data/html;
    index index.html index.htm index.php;

    server_name _;

    #ssl_certificate 	/config/keys/cert.crt;
    #ssl_certificate_key /config/keys/cert.key;
	#ssl_protocols 		TLSv1.2;

    #ssl_client_certificate	'/config/keys/client_rootca-cert.pem';
    #on|off|optional
    #ssl_verify_client optional;
    #ssl_verify_depth 2;

    client_max_body_size 0;

    location / {
        try_files $uri $uri/ /index.html /index.php?$args =404;
        
        # For atomic directory switches
        disable_symlinks off;

        # directory listings
        autoindex on;
    }


  # Include this file on your nginx.conf to support debian cgi-bin scripts using
  # fcgiwrap
  location /cgi-bin/ {
    # Disable gzip (it makes scripts feel slower since they have to complete
    # before getting gzipped)
    gzip off;

    # Set the root to /usr/lib (inside this location this means that we are
    # giving access to the files under /usr/lib/cgi-bin)
    root  /usr/lib;

    # Fastcgi socket
    fastcgi_pass  unix:/var/run/fcgiwrap.socket;

    # Fastcgi parameters, include the standard ones
    include /etc/nginx/fastcgi_params;

    fastcgi_split_path_info ^(.+\.go)(.*)$;

    # Adjust non standard parameters (SCRIPT_FILENAME)
    fastcgi_param SCRIPT_FILENAME  /usr/lib$fastcgi_script_name;

    fastcgi_param PATH_INFO $fastcgi_path_info;
    fastcgi_param CSAF_CONFIG /config/csaf/config.toml;

    fastcgi_param SSL_CLIENT_VERIFY $ssl_client_verify;
    fastcgi_param SSL_CLIENT_S_DN $ssl_client_s_dn;
    fastcgi_param SSL_CLIENT_I_DN $ssl_client_i_dn;
  }

}


